#!/usr/bin/env python3
#
# landscape-clean-decommissioned - Go through landscape list of computers not
# reporting, then delete any that no longer resolve in DNS.

import requests
import socket
import sys

ACCESS_KEY    = 'J71M9C25WH9DPC3GFMP7'
ACCESS_SECRET = '0HWIlcJ/ndD9vI3PFbcGuZnYZH2RSe9RAoQOZaWh'

BASE_URL = 'https://landscape.canonical.com/api/v2/'

# Do a DNS lookup to see if the host exists or not.
def host_exists(hostname):
    try:
        ip_address = socket.gethostbyname(hostname)
        return True
    except socket.gaierror as e:
        return False

# Log in to get an access token for further requests.
login = {
    'access_key': ACCESS_KEY,
    'secret_key': ACCESS_SECRET,
}
headers =  {"Content-Type":"application/json"}
response = requests.post(BASE_URL + 'login/access-key', json=login, headers=headers)

if response.status_code != 200:
    sys.exit(f"Failed to log in: {response.status_code}")
response_data = response.json()
token = response_data['token']

# Get all machines with alerts for being offline.
computer_search = {
    'query': { 'alert': 'computer-offline' }
}
headers =  {"Authorization": f"Bearer {token}"}
response = requests.get(BASE_URL + 'computers', json=computer_search, headers=headers)
if response.status_code != 200:
    sys.exit(f"Failed to get offline computers: {response.status_code}")
response_data = response.json()

# Go through and for each found computer, check if the hostname exists and
# delete if not.
for computer in response_data['results']:
    if not host_exists(computer['hostname']):
        print("%s\t%s\t%s" % (computer['hostname'], computer['id'], computer['last_exchange_time']))

        # Actually delete the computers.
        confirm = { 'computer_title': computer['title'] }
        response = requests.post(BASE_URL + f"computers/{computer['id']}/archive", json=confirm, headers=headers)
        if response.status_code != 200:
            print(response.json())
#            print(computer)
            sys.exit(f"Failed to get delete computer {computer['hostname']}: {response.status_code}")

