#!/usr/bin/env ruby
#
# Compares which machines are on old puppetdb to new puppetdb

require 'json'
require 'httparty'
require 'csv'

# Default settings.
FACTS = %w(ipaddress minsec_level stack operatingsystem operatingsystemrelease).freeze

@puppetdbs = {
  'old' => 'http://sulpuppet-db.stanford.edu:8080/pdb/query/v4',
  'new' => 'https://dlss-openvoxdb.stanford.edu/pdb/query/v4',
}

#############################################################################
# PuppetDB functions
#############################################################################

def request(server, endpoint, query = nil, payload = {})
  responses = []
  options = { 'query' => query.to_json }
  payload.each do |k, v|
    options[k.to_s] = v
  end

  response = HTTParty.get("#{server}/#{endpoint}", body: options, verify: false)
  tmp_rsp = JSON.parse response.body
  tmp_rsp.each do |r|
    responses.push(r)
  end

  responses
end

def fact_request(server, endpoint, name, payload = {})
  responses = []

  response = HTTParty.get("#{server}/#{endpoint}/#{name}",
                          timeout: 120,
                         )
  tmp_rsp = JSON.parse response.body
  tmp_rsp.each do |r|
    responses.push(r)
  end

  responses
end

#############################################################################
# Common functions
#############################################################################

# Do a query for all nodes on a puppetdb server.
def node_data(server)
  hosts = {}
  response = request(server, 'nodes', ['~', ['fact', 'fqdn'], '^.*$'])
  response.each do |r|
    hostname = r['certname'] || r['name']
    hosts[hostname] = r
  end

  hosts
end

# Given the name of a class, return all hosts that use that class.
def servers_with_fact(server, factname)
  servers = {}
  response = fact_request(server, 'facts', factname)
  response.each do |r|
    hostname = r['certname'] || r['name']
    factname = r['value']
    servers[hostname] = factname
  end

  servers
end

#############################################################################
# Main routine
#############################################################################

oldhosts = {}
facts   = []
ARGV.each do |fact_name|
  facts.push(fact_name)
  s = servers_with_fact(@puppetdbs['old'], fact_name)
  s.keys.each do |host|
    oldhosts[host] = {} unless oldhosts.key?(host)
    oldhosts[host][fact_name] = s[host]
  end
end

newhosts = {}
newhosts = node_data(@puppetdbs['new'])
oldhosts.keys.sort.each do |old|
  next if newhosts.keys.include?(old)

  ordered = []
  facts.each do |fact|
    if oldhosts[old].key?(fact)
      fact_value = oldhosts[old][fact]
    else
      fact_value = '-'
    end
    ordered.push(fact_value)

  end
  fact_output = ordered.join ("\t")
  puts "#{old}\t#{fact_output}"
end

