#!/usr/bin/env ruby

# This is a simple puppetdb wrapper that prints all servers in a list of stacks
# from the command line.

require 'puppetdb'

# Get the servers to act on from given stack names.
stack_hostnames = []
client = PuppetDB::Client.new(server: 'http://sulpuppet4-db.stanford.edu:8080')
response = client.request('facts', ['=', 'name', 'stack'])
stack_hostnames << response.data.collect { |x| x['certname'] }
stack_hostnames.flatten!

all_hostnames = []
response = client.request('nodes', ['~', 'certname', '.*'])
all_hostnames << response.data.collect { |x| x['certname'] }
all_hostnames.flatten!

all_hostnames.sort.each do |host|
  next if stack_hostnames.include?(host)
  puts host
end
